#!/usr/bin/env bash

path=
line=
while read; do
    if [[ $REPLY =~ ---\ a/.* ]]; then
        continue
    elif [[ $REPLY =~ \+\+\+\ b/([^\ ]+).* ]]; then
        path=${BASH_REMATCH[1]}
    elif [[ $REPLY =~ @@\ -[0-9]+(,[0-9]+)?\ \+([0-9]+)(,[0-9]+)?\ @@.* ]]; then
        line=${BASH_REMATCH[2]}
    elif [[ ${REPLY:0:1} =~ [\ +-] ]]; then
        echo "$path:$line:$REPLY"
        if [[ ${REPLY:0:1} != - ]]; then
            ((line++))
        fi
    fi
done
