#!/bin/bash

function parse_git_branch {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/' -e 's/)//' -e 's/(//'
}

function open_branch {
  open "https://`repo_root`/tree/`parse_git_branch`"
}

open_branch
